import { chromium } from "@playwright/test";
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 390, height: 844 } });
page.setDefaultTimeout(90000);
await page.goto("http://localhost:3000/login", { timeout: 90000 });
await page.screenshot({ path: "/tmp/login-pw.png" });
await page.locator('#email').fill("j@iconluxurygroup.com");
await page.locator('#password').fill("wrong");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForTimeout(3000);
console.log("wrong password rejected:", (await page.locator("text=That didn't work").count()) > 0);
await page.locator('#password').fill("Icon@1234");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL("http://localhost:3000/", { timeout: 90000 });
await page.waitForTimeout(4000);
await page.screenshot({ path: "/tmp/after-login.png" });
console.log("BOOTSTRAP LOGIN OK");
await b.close();
