import { chromium } from "@playwright/test";
const b = await chromium.launch();
const page = await b.newPage();
page.setDefaultTimeout(90000);
await page.goto("http://localhost:3000/login", { timeout: 90000 });
await page.locator('#email').fill("jonc@iconluxurygroup.com");
await page.locator('#password').fill("Icon@1234");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL("http://localhost:3000/", { timeout: 90000 });
await b.close();
