import { chromium } from "@playwright/test";
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1380, height: 1100 } });
page.setDefaultTimeout(90000);
await page.goto("http://localhost:3000/login", { timeout: 90000 });
await page.locator('input').first().fill("admin@ourdomain.com");
await page.getByRole("button", { name: /continue/i }).click();
await page.waitForURL("http://localhost:3000/", { timeout: 90000 });
await page.goto("http://localhost:3000/pos");
await page.waitForTimeout(5000);
await page.screenshot({ path: "/tmp/pos-list.png" });
await page.locator("tbody a").first().click();
await page.waitForTimeout(6000);
await page.screenshot({ path: "/tmp/po-detail.png", fullPage: true });
await b.close();
console.log("SHOTS OK");
