import { chromium } from "@playwright/test";
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1380, height: 900 } });
page.setDefaultTimeout(90000);
await page.goto("http://localhost:3000/login", { timeout: 90000 });
await page.locator('#email').fill("jonc@iconluxurygroup.com");
await page.locator('#password').fill("Icon@1234");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL("http://localhost:3000/", { timeout: 90000 });
await page.goto("http://localhost:3000/order-forms");
await page.waitForTimeout(2500);
await page.locator('a[href^="/order-forms/"]').first().click();
await page.waitForURL(/order-forms\/.+/, { timeout: 30000 });
await page.waitForTimeout(3500);
await page.screenshot({ path: "/tmp/container-card2.png" });
console.log("ON:", page.url());
await b.close();
